import { describe, expect, it } from "vitest";
import {
  createPendingScrollSync,
  calculateScrollProgress,
  mapScrollToTarget,
  type ScrollMetrics,
} from "../src/lib/utils/scroll-sync";

describe("calculateScrollProgress", () => {
  it("returns zero when nothing can scroll", () => {
    const source: ScrollMetrics = { scrollTop: 50, scrollHeight: 400, clientHeight: 400 };
    expect(calculateScrollProgress(source)).toBe(0);
  });

  it("returns normalized progress within the scroll range", () => {
    const source: ScrollMetrics = { scrollTop: 150, scrollHeight: 500, clientHeight: 200 };
    expect(calculateScrollProgress(source)).toBeCloseTo(0.5);
  });

  it("clamps progress to one when scrollTop exceeds the range", () => {
    const source: ScrollMetrics = { scrollTop: 900, scrollHeight: 500, clientHeight: 200 };
    expect(calculateScrollProgress(source)).toBe(1);
  });
});

describe("mapScrollToTarget", () => {
  it("maps source progress into the target scroll range", () => {
    const source: ScrollMetrics = { scrollTop: 150, scrollHeight: 500, clientHeight: 200 };
    expect(mapScrollToTarget(source, 1000, 400)).toBeCloseTo(300);
  });

  it("returns zero when the target cannot scroll", () => {
    const source: ScrollMetrics = { scrollTop: 150, scrollHeight: 500, clientHeight: 200 };
    expect(mapScrollToTarget(source, 400, 400)).toBe(0);
  });
});

describe("createPendingScrollSync", () => {
  it("ignores the later scroll event generated by a synced scroll position", () => {
    const pending = createPendingScrollSync();
    pending.mark(240);

    expect(pending.shouldIgnore(240)).toBe(true);
  });

  it("clears the pending synced scroll after ignoring it once", () => {
    const pending = createPendingScrollSync();
    pending.mark(240);

    expect(pending.shouldIgnore(240)).toBe(true);
    expect(pending.shouldIgnore(240)).toBe(false);
  });

  it("treats a different scroll position as user input and clears the pending state", () => {
    const pending = createPendingScrollSync();
    pending.mark(240);

    expect(pending.shouldIgnore(200)).toBe(false);
    expect(pending.shouldIgnore(240)).toBe(false);
  });
});
